name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod

    - name: Test
      run: |
        go install golang.org/x/tools/cmd/goyacc@latest
        goyacc -o parser/parser.go parser/parser.go.y
        go test $(go list ./... | grep -v /wasm) -coverprofile=cover_broken.out
        cat cover_broken.out | grep -v yaccpar | grep -v .y > cover.out

    - name: Coverage
      env:
        TESTCOVERAGE_THRESHOLD: 100.0
      run: |
        totalCoverage=`go tool cover -func=cover.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
        echo "$totalCoverage >= $TESTCOVERAGE_THRESHOLD"
        if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
          echo "OK"
        else
          echo "NG"
          exit 1
        fi

    - name: Build
      run: go build -v
